services:
    app:
        build:
            context: '.'
            dockerfile: docker/Dockerfile.dev
        image: 'books/app-dev'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:8000'
        environment:
            APP_ENV: '${APP_ENV:-local}'
            APP_KEY: '${APP_KEY}'
            DB_CONNECTION: pgsql
            DB_HOST: pgsql
            DB_PORT: 5432
            DB_DATABASE: '${DB_DATABASE:-books}'
            DB_USERNAME: '${DB_USERNAME:-sail}'
            DB_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - './backend:/var/www/html'
        networks:
            - sail
        depends_on:
            pgsql:
                condition: service_healthy

    pgsql:
        image: 'postgres:16-alpine'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-books}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE:-books}'
                - '-U'
                - '${DB_USERNAME:-sail}'
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
