services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-demo
    hostname: gitlab.local
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "2222:22"
    environment:
      GITLAB_ROOT_PASSWORD: 'Sup3rS3cr3t#2026!'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8090'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - demo-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner-demo
    restart: unless-stopped
    volumes:
      - ../runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - demo-network

networks:
  demo-network:
    name: demo-network
